architecture: replication

auth:
  rootPassword: "123456"
  database: db_name
  username: username
  password: password

volumePermissions:
  enabled: true


secondary:
  name: secondary
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for EKS volumes
    storageClass: gp3


