# these are all the values required for a successful deployment of java-app on an EKS cluster.

appName: java-mysql-app
appImage: khovic/java-mysql-app
appVersion: 2.0.16
appReplicas: 3
containerPort: 8080

containerEnvVars:
- name: DB_USER
  value: ${DB_USER}
- name: DB_PWD
  value: ${DB_PWD}
- name: DB_SERVER
  value: "mysql-primary.default"
- name: DB_NAME
  value: ${DB_NAME}

servicePort: 8080
serviceType: ClusterIP

ingressNamespace: default
ingressApiVersion: networking.k8s.io/v1
ingressHost: a7173ccd0b62f4703abd76c8821f5ce3-2061138151.eu-central-1.elb.amazonaws.com

configName: java-app-config
dbName: ${DB_NAME}
dbServer: mysql-primary.default

secretName: db-secret
secretData: 
  DB_USER: ${DB_USER}
  DB_PWD: ${DB_PWD}
  DB_NAME: ${DB_NAME}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
