architecture: replication

auth:
  rootPassword: "${MYSQL_ROOT_PASSWORD}"
  database: db_name
  username: ${DB_USER}
  password: ${DB_PWD}

primary:
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for EKS volumes
    storageClass: gp2

volumePermissions:
  enabled: true


secondary:
  name: secondary
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for EKS volumes
    storageClass: gp2-sec


